# Generated by Django 4.2.11 on 2026-04-07 23:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Firebase UID')),
                ('matricule', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Matricule')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid WhatsApp number', regex='^\\+?1?\\d{9,15}$')])),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('CEO', 'Chief Executive Officer'), ('CTO', 'Chief Technology Officer'), ('COO', 'Chief Operations Officer'), ('INV', 'Investor'), ('DESIGNER', 'Designer'), ('SCHOOL_ADMIN', 'School Administrator'), ('SUB_ADMIN', 'Sub Administrator'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('BURSAR', 'Bursar'), ('LIBRARIAN', 'Librarian')], db_index=True, default='STUDENT', max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_license_paid', models.BooleanField(default=False)),
                ('ai_request_count', models.IntegerField(default=0)),
                ('annual_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Annual Average')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='schools.school')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['matricule'], name='users_matricu_5d6274_idx'), models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['role'], name='users_role_0ace22_idx'), models.Index(fields=['school'], name='users_school__965c22_idx')],
            },
        ),
    ]
