# Generated by Codex on 2026-04-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_title', models.CharField(max_length=255)),
                ('primary_share_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_primary_founder', models.BooleanField(default=False)),
                ('can_be_removed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founder_profile', to='users.user')),
            ],
            options={
                'db_table': 'founder_profiles',
                'ordering': ['-is_primary_founder', 'user__date_joined'],
            },
        ),
        migrations.CreateModel(
            name='FounderShareAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founder_share_adjustments_added', to='users.user')),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_adjustments', to='users.founderprofile')),
            ],
            options={
                'db_table': 'founder_share_adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='founderprofile',
            index=models.Index(fields=['is_primary_founder'], name='founder_pro_is_prim_4ef813_idx'),
        ),
        migrations.AddIndex(
            model_name='founderprofile',
            index=models.Index(fields=['can_be_removed'], name='founder_pro_can_be__7be4be_idx'),
        ),
        migrations.AddIndex(
            model_name='foundershareadjustment',
            index=models.Index(fields=['founder', 'created_at'], name='founder_sha_founder_f3e8e4_idx'),
        ),
    ]
