# Generated by Django 4.2.11 on 2026-04-07 23:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insight_type', models.CharField(choices=[('weekly_performance', 'Weekly Performance'), ('attendance_alert', 'Attendance Alert'), ('honour_roll_prediction', 'Honour Roll Prediction'), ('dropout_risk', 'Dropout Risk')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('target_role', models.CharField(help_text='Comma-separated roles that should see this insight (e.g., executive,principal,teacher)', max_length=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('study_plan', 'Study Plan Generation'), ('grade_analysis', 'Grade Analysis'), ('attendance_insight', 'Attendance Insight'), ('report_summary', 'Report Summary'), ('subject_recommendation', 'Subject Recommendation'), ('exam_prep', 'Exam Preparation'), ('parent_report', 'Parent Report'), ('teacher_insight', 'Teacher Insight'), ('general', 'General Query')], max_length=50)),
                ('prompt', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('model_used', models.CharField(default='llama-3.3-70b-versatile', max_length=100)),
                ('tokens_used', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
