# Generated by Django 4.2.11 on 2026-04-07 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_features', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='schools.school'),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['user', '-created_at'], name='ai_features_user_id_9771aa_idx'),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['school', '-created_at'], name='ai_features_school__8b0167_idx'),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['status', 'created_at'], name='ai_features_status_0a8ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['request_type', '-created_at'], name='ai_features_request_8a3f19_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['school', 'is_active'], name='ai_features_school__463683_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['insight_type', '-created_at'], name='ai_features_insight_456850_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['expires_at', 'is_active'], name='ai_features_expires_54d8c8_idx'),
        ),
    ]
