# Generated by Django 4.2.11 on 2026-04-07 23:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(help_text='e.g., GBHS-D', max_length=50, primary_key=True, serialize=False, verbose_name='School ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=50)),
                ('principal', models.CharField(max_length=255)),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='school_banners/')),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('Littoral', 'Littoral'), ('Centre', 'Centre'), ('East', 'East'), ('North', 'North'), ('South', 'South'), ('West', 'West'), ('Northwest', 'Northwest'), ('Southwest', 'Southwest'), ('South-West', 'South-West'), ('North-West', 'North-West')], max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('sub_division', models.CharField(max_length=100)),
                ('city_village', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('student_count', models.IntegerField(default=0)),
                ('teacher_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_expiry', models.DateField(blank=True, null=True)),
                ('max_students', models.IntegerField(default=500)),
                ('max_teachers', models.IntegerField(default=50)),
                ('academic_year', models.CharField(default='2024-2025', help_text='e.g., 2024-2025', max_length=20)),
                ('term', models.CharField(choices=[('First', 'First Term'), ('Second', 'Second Term'), ('Third', 'Third Term')], default='First', max_length=20)),
                ('allow_ai_features', models.BooleanField(default=True)),
                ('ai_request_limit', models.IntegerField(default=1000)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='schools.school')),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
                'db_table': 'school_settings',
            },
        ),
    ]
