# Generated by Django 4.2.11 on 2026-04-07 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='principal_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_principal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['status'], name='schools_status_0f17fc_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['region'], name='schools_region_c77189_idx'),
        ),
    ]
