# Generated by Django 4.2.11 on 2026-04-07 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('grades', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sequence',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='schools.school'),
        ),
        migrations.AddField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='schools.school'),
        ),
        migrations.AddField(
            model_name='grade',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.sequence'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.subject'),
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annualresult',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_results', to='schools.school'),
        ),
        migrations.AddField(
            model_name='annualresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_results', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='termresult',
            index=models.Index(fields=['student', 'academic_year'], name='grades_term_student_a31792_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='termresult',
            unique_together={('student', 'academic_year', 'term')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'level'], name='grades_subj_school__82f6cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'code')},
        ),
        migrations.AddIndex(
            model_name='sequence',
            index=models.Index(fields=['school', 'academic_year', 'is_active'], name='grades_sequ_school__128068_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together={('school', 'academic_year', 'term', 'name')},
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'sequence'], name='grades_grad_student_5e82fb_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['subject', 'sequence'], name='grades_grad_subject_72554c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='annualresult',
            index=models.Index(fields=['student', 'academic_year'], name='grades_annu_student_4e74a0_idx'),
        ),
        migrations.AddIndex(
            model_name='annualresult',
            index=models.Index(fields=['school', 'academic_year'], name='grades_annu_school__0cdd7f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='annualresult',
            unique_together={('student', 'academic_year')},
        ),
    ]
