# Generated by Django 4.2.11 on 2026-04-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('remark_type', models.CharField(choices=[('Commendation', 'Commendation'), ('Warning', 'Warning'), ('Observation', 'Observation'), ('Disciplinary', 'Disciplinary')], max_length=20)),
                ('is_confidential', models.BooleanField(default=False)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
