# Generated by Django 4.2.11 on 2026-04-07 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_initial'),
        ('staff_remarks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffremark',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_remarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffremark',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='staffremark',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_remarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='staffremark',
            index=models.Index(fields=['staff', 'school'], name='staff_remar_staff_i_5f74b2_idx'),
        ),
        migrations.AddIndex(
            model_name='staffremark',
            index=models.Index(fields=['admin', 'school'], name='staff_remar_admin_i_6c8636_idx'),
        ),
    ]
