# Generated by Django 4.2.11 on 2026-04-07 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_testimonies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testimony',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityblog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.communityblog'),
        ),
        migrations.AddIndex(
            model_name='testimony',
            index=models.Index(fields=['status', 'created_at'], name='community_t_status_c2302f_idx'),
        ),
        migrations.AddIndex(
            model_name='communityblog',
            index=models.Index(fields=['is_published', 'published_at'], name='community_c_is_publ_b1bd26_idx'),
        ),
        migrations.AddIndex(
            model_name='communityblog',
            index=models.Index(fields=['slug'], name='community_c_slug_acc7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['blog', 'is_approved'], name='community_b_blog_id_516fb4_idx'),
        ),
    ]
