# Generated by Django 4.2.11 on 2026-04-07 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='XAF', max_length=10)),
                ('payment_method', models.CharField(choices=[('Mobile Money', 'Mobile Money'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash')], max_length=20)),
                ('phone', models.CharField(help_text='Payment phone number', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='New', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=255)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
