# Generated by Django 4.2.11 on 2026-04-07 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportcontribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportcontribution',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='supportcontribution',
            index=models.Index(fields=['user', 'status'], name='support_sup_user_id_e0972a_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcontribution',
            index=models.Index(fields=['status', 'created_at'], name='support_sup_status_a0f485_idx'),
        ),
    ]
