# Generated by Django 4.2.11 on 2026-04-07 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent'), ('TEACHER', 'Teacher'), ('BURSAR', 'Bursar'), ('LIBRARIAN', 'Librarian'), ('SCHOOL_ADMIN', 'School Admin'), ('SUB_ADMIN', 'Sub Admin')], max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='XAF', max_length=3)),
            ],
            options={
                'verbose_name': 'Platform Fee',
                'verbose_name_plural': 'Platform Fees',
                'db_table': 'platform_fees',
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='EduIgnite', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='platform/')),
                ('payment_deadline', models.DateField(blank=True, null=True)),
                ('honour_roll_threshold', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('fees', models.JSONField(default=dict)),
                ('tutorial_links', models.JSONField(default=dict)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(blank=True, default='eduignitecmr@gmail.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
                'db_table': 'platform_settings',
            },
        ),
        migrations.CreateModel(
            name='PublicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('article', 'Article'), ('news', 'News')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Public Event',
                'verbose_name_plural': 'Public Events',
                'db_table': 'public_events',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tutorial Link',
                'verbose_name_plural': 'Tutorial Links',
                'db_table': 'tutorial_links',
                'ordering': ['role', 'title'],
            },
        ),
    ]
